
package com.ipartek.peliculas;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "peliculaservice", targetNamespace = "http://com.ipartek.formacion/types", wsdlLocation = "http://localhost:8080/webservices-jwxs/peliculasws?wsdl")
public class Peliculaservice
    extends Service
{

    private final static URL PELICULASERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.ipartek.peliculas.Peliculaservice.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.ipartek.peliculas.Peliculaservice.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8080/webservices-jwxs/peliculasws?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8080/webservices-jwxs/peliculasws?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        PELICULASERVICE_WSDL_LOCATION = url;
    }

    public Peliculaservice(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Peliculaservice() {
        super(PELICULASERVICE_WSDL_LOCATION, new QName("http://com.ipartek.formacion/types", "peliculaservice"));
    }

    /**
     * 
     * @return
     *     returns PeliculaServiceWSImp
     */
    @WebEndpoint(name = "PeliculaServiceWSImpPort")
    public PeliculaServiceWSImp getPeliculaServiceWSImpPort() {
        return super.getPort(new QName("http://com.ipartek.formacion/types", "PeliculaServiceWSImpPort"), PeliculaServiceWSImp.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PeliculaServiceWSImp
     */
    @WebEndpoint(name = "PeliculaServiceWSImpPort")
    public PeliculaServiceWSImp getPeliculaServiceWSImpPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://com.ipartek.formacion/types", "PeliculaServiceWSImpPort"), PeliculaServiceWSImp.class, features);
    }

}
