
package com.ipartek.peliculas;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "PeliculaServiceWSImp", targetNamespace = "http://com.formacion.ipartek/types")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PeliculaServiceWSImp {


    /**
     * 
     * @param arg0
     * @return
     *     returns com.ipartek.peliculas.PeliculaMensaje
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obtenerpoid", targetNamespace = "http://com.formacion.ipartek/types", className = "com.ipartek.peliculas.Obtenerpoid")
    @ResponseWrapper(localName = "obtenerpoidResponse", targetNamespace = "http://com.formacion.ipartek/types", className = "com.ipartek.peliculas.ObtenerpoidResponse")
    public PeliculaMensaje obtenerpoid(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

}
